//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employee_managementEntities : DbContext
    {
        public employee_managementEntities()
            : base("name=employee_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<job_offers> job_offers { get; set; }
        public virtual DbSet<job_applicants> job_applicants { get; set; }
        public virtual DbSet<employee_sick_leaves> employee_sick_leaves { get; set; }
        public virtual DbSet<jobs_log> jobs_log { get; set; }
    }
}
