//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string skill { get; set; }
        public string NIF { get; set; }
        public string NISS { get; set; }
        public string passport { get; set; }
        public string visa { get; set; }
        public string residence_card { get; set; }
        public string SEF { get; set; }
        public string boarding_pass { get; set; }
        public string bank_account_number { get; set; }
        public string working_shift { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string comments { get; set; }
        public string nif_number { get; set; }
        public string dob { get; set; }
        public string sex { get; set; }
        public string driving_license { get; set; }
        public string nationality { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    }
}
