//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_sick_leaves
    {
        public int sick_leave_id { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string medical_document { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> job_id { get; set; }
    }
}
