//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public string job_title { get; set; }
        public string job_details { get; set; }
        public Nullable<System.DateTime> job_start_date { get; set; }
        public Nullable<System.DateTime> job_end_date { get; set; }
        public string job_duration { get; set; }
        public string job_type { get; set; }
        public string job_status { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
