//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_offers
    {
        public int job_offer_id { get; set; }
        public string job_title { get; set; }
        public string job_details { get; set; }
        public Nullable<System.DateTime> job_last_date { get; set; }
        public string job_type { get; set; }
        public string job_shift { get; set; }
        public string job_location { get; set; }
        public string job_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
