//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_applicants
    {
        public int applicant_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string dob { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string nif_number { get; set; }
        public string nationality { get; set; }
        public string NIF { get; set; }
        public string NISS { get; set; }
        public string passport_number { get; set; }
        public string passport_validity_year { get; set; }
        public string medical_examination { get; set; }
        public string exam_date { get; set; }
        public Nullable<System.DateTime> apply_date { get; set; }
        public string status { get; set; }
        public string job_offer_type { get; set; }
        public Nullable<int> job_offer_id { get; set; }
    }
}
